### ISSUE TITLE
One-Step-Processing error

### ISSUE THREAD

**Issue by mattiaagostino** [stefaneichert/OpenLidarToolbox#3]
Hi, 
i'm a student from the University of Padua, i would like to use Open Lidar Toolbox for detection of archaeological remains over an area with very dense forest cover. I have a point cloud file (.laz) obtained from a lidar relief and subsequently cleaned and treated with qt modeler. From this file .laz i would like to test your plug in but an error occur:
"Traceback (most recent call last):
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStools\lasground.py", line 75, in processAlgorithm
LAStoolsUtils.runLAStools(commands, feedback)
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStoolsUtils.py", line 61, in runLAStools
feedback.pushConsoleInfo(output.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 17: invalid start byte

Execution failed after 0.03 secondi"
I already check your FAQ and i notice that a similar error happens when there is a special character but thi is not my case. Any suggestion?
My version of QGIS is 3.22.5
Many thanks

**Comment by stefaneichert** [comment]
Hi!
Thanks for the feedback. Could you try to process your file with the "LAStools - file processing points - lasground" algorithm from the processing toolbox, in order to exclude that the error is within LAStools themselves.
Or alternatively attach the file here, so I can check it out on my system.
best regards,
Stefan

**Comment by mattiaagostino** [comment]
I process the file with the algorithm lasgroud and i have the same error:
LAStools command line
C:/Program Files/LAStools\bin\lasground -i "C:\Users\User\Desktop\UNI\MASTER GIS\Stage Master\DATI\Archetipo\pd.laz" -archaeology
LAStools console output
Traceback (most recent call last):
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStools\lasground.py", line 75, in processAlgorithm
LAStoolsUtils.runLAStools(commands, feedback)
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStoolsUtils.py", line 61, in runLAStools
feedback.pushConsoleInfo(output.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 17: invalid start byte

Execution failed after 0.03 secondi

What i have to do now?

**Comment by stefaneichert** [comment]
Hi! I guess, the problem is in your file, as it does not work with LAStools alone either. You could try to convert it to some other format and then convert it back using LAStools or Whitebox etc.. Maybe that helps?

**Comment by mattiaagostino** [comment]
Hi Stefan,
in which format you suggest me to convert it?
If you give me your email i can send you the file, maybe you can understand better the problem.
Thank you

**Comment by mattiaagostino** [comment]
I try to save the file in .shp, then convert it with LAStool, here the response:
In avvio l'algoritmo 'shp2las' …
Parametri in ingresso:
{ 'ADDITIONAL_OPTIONS' : '', 'GUI' : False, 'INPUT_GENERIC' : 'C:\\Users\\User\\Desktop\\UNI\\MASTER GIS\\Stage Master\\DATI\\Cloud_prova\\pd - Cloud.shp', 'SCALE_FACTOR_XY' : 0.01, 'SCALE_FACTOR_Z' : 0.01, 'VERBOSE' : False }

LAStools command line
C:/Program Files/LAStools\bin\shp2las -i "C:\Users\User\Desktop\UNI\MASTER GIS\Stage Master\DATI\Cloud_prova\pd - Cloud.shp" -set_scale_factor 0.01 0.01 0
LAStools console output
Traceback (most recent call last):
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStools\shp2las.py", line 55, in processAlgorithm
LAStoolsUtils.runLAStools(commands, feedback)
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools\LAStoolsUtils.py", line 61, in runLAStools
feedback.pushConsoleInfo(output.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 17: invalid start byte

Execution failed after 0.06 secondi

Caricamento layer
Algoritmo 'shp2las' terminato

Any suggestion?

**Comment by stefaneichert** [comment]
The problem is caused by spaces in the path name leading to the LasTools executables. Having a path without spaces solves this problem.
