### ISSUE TITLE
DEM Hillshade Question 

### ISSUE THREAD

**Issue by lunar-studio** [stefaneichert/OpenLidarToolbox#4]
Hi Stefan,

Thank you for the genius work!!! It’s a pretty incredible contribution. 
I have more of a question than an actual issue.

I am a 3D modeler/artist (with a anthro background) learning QGIS this week and was seeing if it were possible to remove vegetation in LIDAR information. It appears your tools do a fantastic job at this. However, when I try to view the DFM using QGIS2three or the built-in 3d viewer, the model becomes extremely rough, exaggerated, and it loses all of the fine resolution.

Do you have any suggestions on workflow in order to create a 3D model that portrays the terrain accurately without vegetation? I realize this is probably a loaded question, but any quick tips would be greatly appreciated.

Kind Regards,

-Charlie

**Comment by stefaneichert** [comment]
Hi Charlie,
thanks for the feedback. I think your question is more a generally QGIS related one and not specific for OpenLiDAR Toolbox. However, I guess you could search for ways to create a 3D model/mesh/tin from the elevation data of the DFM raster layer and maybe add the visualisations like hillshades etc. as a texture.
